class TeamIds {
  static const Map<String, String> ncaaFootball = {
    'Air Force Falcons': '2005',
    'Akron Zips': '2006',
    'Alabama Crimson Tide': '333',
    'Appalachian State Mountaineers': '2026',
    'Arizona State Sun Devils': '9',
    'Arizona Wildcats': '12',
    'Arkansas Razorbacks': '8',
    'Arkansas State Red Wolves': '2032',
    'Army Black Knights': '349',
    'Auburn Tigers': '2',
    'BYU Cougars': '252',
    'Ball State Cardinals': '2050',
    'Baylor Bears': '239',
    'Boise State Broncos': '68',
    'Boston College Eagles': '103',
    'Bowling Green Falcons': '189',
    'Buffalo Bulls': '2084',
    'California Golden Bears': '25',
    'Central Michigan Chippewas': '2117',
    'Charlotte 49ers': '2429',
    'Cincinnati Bearcats': '2132',
    'Clemson Tigers': '228',
    'Coastal Carolina Chanticleers': '324',
    'Colorado Buffaloes': '38',
    'Colorado State Rams': '36',
    'Duke Blue Devils': '150',
    'East Carolina Pirates': '151',
    'Eastern Michigan Eagles': '2199',
    'Florida Atlantic Owls': '2226',
    'Florida Gators': '57',
    'Florida International Panthers': '2229',
    'Florida State Seminoles': '52',
    'Fresno State Bulldogs': '278',
    'Georgia Bulldogs': '61',
    'Georgia Southern Eagles': '290',
    'Georgia State Panthers': '2247',
    'Georgia Tech Yellow Jackets': '59',
    'Hawaii Rainbow Warriors': '62',
    'Houston Cougars': '248',
    'Illinois Fighting Illini': '356',
    'Indiana Hoosiers': '84',
    'Iowa Hawkeyes': '2294',
    'Iowa State Cyclones': '66',
    'Jacksonville State Gamecocks': '55',
    'James Madison Dukes': '256',
    'Kansas Jayhawks': '2305',
    'Kansas State Wildcats': '2306',
    'Kennesaw State Owls': '2369',
    'Kent State Golden Flashes': '2309',
    'Kentucky Wildcats': '96',
    'LSU Tigers': '99',
    'Liberty Flames': '2335',
    'Louisiana Ragin Cajuns': '309',
    'Louisiana Tech Bulldogs': '2348',
    'Louisville Cardinals': '97',
    'Marshall Thundering Herd': '276',
    'Maryland Terrapins': '120',
    'Memphis Tigers': '235',
    'Miami (OH) RedHawks': '193',
    'Miami Hurricanes': '2390',
    'Michigan State Spartans': '127',
    'Michigan Wolverines': '130',
    'Middle Tennessee Blue Raiders': '2393',
    'Minnesota Golden Gophers': '135',
    'Mississippi State Bulldogs': '344',
    'Missouri Tigers': '142',
    'NC State Wolfpack': '152',
    'Navy Midshipmen': '2426',
    'Nebraska Cornhuskers': '158',
    'Nevada Wolf Pack': '2440',
    'New Mexico Lobos': '167',
    'New Mexico State Aggies': '166',
    'North Carolina Tar Heels': '153',
    'North Texas Mean Green': '249',
    'Northern Illinois Huskies': '2459',
    'Northwestern Wildcats': '77',
    'Notre Dame Fighting Irish': '87',
    'Ohio Bobcats': '195',
    'Ohio State Buckeyes': '194',
    'Oklahoma Sooners': '201',
    'Oklahoma State Cowboys': '197',
    'Old Dominion Monarchs': '295',
    'Ole Miss Rebels': '145',
    'Oregon Ducks': '2483',
    'Oregon State Beavers': '204',
    'Penn State Nittany Lions': '213',
    'Pittsburgh Panthers': '221',
    'Purdue Boilermakers': '2509',
    'Rice Owls': '242',
    'Rutgers Scarlet Knights': '164',
    'SMU Mustangs': '2567',
    'Sam Houston State Bearkats': '2534',
    'San Diego State Aztecs': '21',
    'San Jose State Spartans': '23',
    'South Alabama Jaguars': '6',
    'South Carolina Gamecocks': '2579',
    'South Florida Bulls': '58',
    'Southern Mississippi Golden Eagles': '2572',
    'Stanford Cardinal': '24',
    'Syracuse Orange': '183',
    'TCU Horned Frogs': '2628',
    'Temple Owls': '218',
    'Tennessee Volunteers': '2633',
    'Texas A&M Aggies': '245',
    'Texas Longhorns': '251',
    'Texas State Bobcats': '326',
    'Texas Tech Red Raiders': '2641',
    'Toledo Rockets': '2649',
    'Troy Trojans': '2653',
    'Tulane Green Wave': '2655',
    'Tulsa Golden Hurricane': '202',
    'UAB Blazers': '5',
    'UCF Knights': '2116',
    'UCLA Bruins': '26',
    'UConn Huskies': '41',
    'UL Monroe Warhawks': '2433',
    'UMass Minutemen': '113',
    'UNLV Rebels': '2439',
    'USC Trojans': '30',
    'UTEP Miners': '2638',
    'UTSA Roadrunners': '2636',
    'Utah State Aggies': '328',
    'Utah Utes': '254',
    'Vanderbilt Commodores': '238',
    'Virginia Cavaliers': '258',
    'Virginia Tech Hokies': '259',
    'Wake Forest Demon Deacons': '154',
    'Washington Huskies': '264',
    'Washington State Cougars': '265',
    'West Virginia Mountaineers': '277',
    'Western Kentucky Hilltoppers': '98',
    'Western Michigan Broncos': '2711',
    'Wisconsin Badgers': '275',
    'Wyoming Cowboys': '2751',
  };
} 